version: "3"

services:
  mysql:
    image: mysql:5.7
    hostname: mysql
#    container_name: mysql2
    networks:
      default:
        aliases:
          - mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: password
    volumes:
      - var_lib_mysql:/var/lib/mysql
    deploy:
      mode: global

  slurmdbd:
    image: cfiddle-cluster:21.08.6.1
    build:
      context: .
    command: ["slurmdbd"]
    hostname: slurmdbd
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - var_log_slurm:/var/log/slurm
#    expose:
#      - 6819
    depends_on:
      - mysql
    deploy:
      mode: global

  slurmctld:
    image: cfiddle-cluster:21.08.6.1
    command: ["slurmctld"]
    hostname: slurmctld
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
#    expose:
#      - 6817
    depends_on:
      - slurmdbd
    deploy:
      mode: global

  c1: &worker
    image: cfiddle-cluster:21.08.6.1
    command: ["slurmd"]
    hostname: c1
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - cfiddle_scratch:/cfiddle_scratch
 #   expose:
 #     - 6818
    depends_on:
      - slurmctld
    deploy:
      mode: global



  c2: &c2
    <<: *worker
    hostname: c2

#  c3: &c3
#    <<: *worker
#    hostname: c3##

#  c4: &c4
#    <<: *worker
#    hostname: c4

#  c6: &c6
#    <<: *worker
#    hostname: c6

#  c5: &c5
#    <<: *worker
#    hostname: c5

#  watcher:
 #   image: cfiddle-cluster:21.08.6.1
#    entrypoint: ["/usr/bin/bash", "-c"]
#3    command: ["while true; do sleep 10;done"]
#    hostname: watcher
#    volumes:
#      - etc_munge:/etc/munge
#      - etc_slurm:/etc/slurm
#      - slurm_jobdir:/data
#      - var_log_slurm:/var/log/slurm
#      - cfiddle_scratch:/cfiddle_scratch
#    depends_on:
#      - slurmctld

volumes:
  etc_munge:
  etc_slurm:
  slurm_jobdir:
  var_lib_mysql:
  var_log_slurm:
  cfiddle_scratch:

