version: "3.3"

services:
  nfs-server:
    image:  erichough/nfs-server
    hostname: nfs-server
    container_name: nfs-server
    environment:
      NFS_EXPORT_0: '/users_home                  *(rw,no_subtree_check)'
    privileged: True
    expose:
      - "111"
      - "2049"
      - "32765"
      - "32767"
#    ports:
#      - "111:111"
#      - "2049:2049"
#      - "32765:32765"
#      - "32767:32767"
#    network_mode: "host"
    volumes:
      - users_home:/users_home
  tester:
    image: ubuntu:jammy
    hostname: tester
    command: "bash -c 'while true; do sleep 30;done'"
    
volumes:
  users_home:
  
#  users_home_nfs:
 #   driver: local
 #   driver_opts:
 #     type: nfs
 #     o: addr=172.29.0.2,nolock,soft,rw
 #     device: :/users_home

#mount nfs-server:/users_home /tmp/mnt  -o nolock


#  docker volume create \
#  --driver local \
#  --opt type=nfs \
#  --opt o=addr=$NFS_SERVER,$NFS_OPTS \
#  --opt device=:$NFS_SHARE \
#  $NFS_VOL_NAME